spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  session:
    timeout: 86400


  datasource:
    url: jdbc:h2:mem:v-shop;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    defer-datasource-initialization: true

server:
  servlet:
    session:
      cookie:
        max-age: 172800
