### 어드민 회원가입
POST http://localhost:8080/auth/adminsignup
Content-Type: application/json

{
  "adminId": "admin1",
  "password": "1234",
  "adminName": "김영한",
  "adminNickname": "호랑이",
  "authorities": ["MemberManage", "SITE_MANAGE"]
}

### 운영자 로그인
POST http://localhost:8080/login/manager
Content-Type: application/json

{
  "adminId": "admin23",
  "password": "1234"
}

### 로그아웃
POST http://localhost:8080/logout

### 세션 정보
POST http://localhost:8080/api/sessionInfo


